language: rust
sudo: required

os:
  - linux
  - osx

cache: cargo
rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - FEATURE=accelerate
    - FEATURE=netlib
    - FEATURE=openblas

matrix:
  exclude:
    - os: linux
      env: FEATURE=accelerate

before_install:
  - curl https://stainless-steel.github.io/travis/fortran.sh | bash

script:
  - cargo test -vv --no-default-features --features=$FEATURE

addons:
  apt:
    sources:
      - kubuntu-backports

    packages:
      - cmake
      - gfortran

notifications:
  email: false
