language: rust
sudo: false

addons:
  apt:
    packages:
      - gfortran

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: EMVyll81L6XVqiD7LgCu80Xob5U3scenro7ZXpB9TziuLzPhfWMx43x1ue84isqDixLjyQZETwjO+fwFt94qv696wGYOth/xQTsVgu4MHUK8mkt6Bf3bsTORQ2f67y6f6vuvvziASiD2bWHcmsyrvzUxgRdwZ/VtodeCMDVeYrM=

notifications:
  email: false
