[package]
name = "lapack"
version = "0.3.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/lapack"
homepage = "https://github.com/stainless-steel/lapack"
documentation = "https://stainless-steel.github.io/lapack"
description = "The package provides an interface to the Linear Algebra PACKage."

[dependencies]
libc = "*"

[dependencies.liblapack-sys]
version = "*"

[dev-dependencies]
assert = "*"
