[package]
name = "lapack"
version = "0.4.1"
authors = [
  "Andrew Straw <strawman@astraw.com>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
license = "MIT"
repository = "https://github.com/stainless-steel/lapack"
homepage = "https://github.com/stainless-steel/lapack"
documentation = "https://stainless-steel.github.io/lapack"
description = "The package provides an interface to the Linear Algebra PACKage."

[dependencies]
complex = "0.7"
lapack-sys = "0.3"
libc = "*"
