[package]
name = "lapack"
version = "0.10.0"
license = "Apache-2.0/MIT"
authors = [
  "Andrew Straw <strawman@astraw.com>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
description = "The package provides an interface to the Linear Algebra PACKage."
documentation = "https://stainless-steel.github.io/lapack"
homepage = "https://github.com/stainless-steel/lapack"
repository = "https://github.com/stainless-steel/lapack"

[features]
default = ["openblas"]

accelerate = ["lapack-sys/accelerate"]
netlib = ["lapack-sys/netlib"]
openblas = ["lapack-sys/openblas"]

[dependencies]
libc = "0.2"

[dependencies.num]
version = "0.1"
default-features = false
features = ["complex"]

[dependencies.lapack-sys]
version = "0.11"
default-features = false
